version: "3"
services:
    db:
        build: ./
        environment:
            SA_PASSWORD: "MssqlPass123"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "1433:1433"
        container_name: db1
        hostname: db1
        volumes:
            - ms-sqlserver-linux-sample-data:/var/opt/mssql
            - ./backup:/backup
volumes:
    ms-sqlserver-linux-sample-data:
        driver: local